<?php

namespace DoctrineProxies\__CG__\App\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Filme extends \App\Model\Filme implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'anoLancamento' => [parent::class, 'anoLancamento', null, 16],
        "\0".parent::class."\0".'capa' => [parent::class, 'capa', null, 16],
        "\0".parent::class."\0".'diretor' => [parent::class, 'diretor', null, 16],
        "\0".parent::class."\0".'genero' => [parent::class, 'genero', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'sinopse' => [parent::class, 'sinopse', null, 16],
        "\0".parent::class."\0".'titulo' => [parent::class, 'titulo', null, 16],
        "\0".parent::class."\0".'trailer' => [parent::class, 'trailer', null, 16],
        'anoLancamento' => [parent::class, 'anoLancamento', null, 16],
        'capa' => [parent::class, 'capa', null, 16],
        'diretor' => [parent::class, 'diretor', null, 16],
        'genero' => [parent::class, 'genero', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'sinopse' => [parent::class, 'sinopse', null, 16],
        'titulo' => [parent::class, 'titulo', null, 16],
        'trailer' => [parent::class, 'trailer', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
